version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000/tcp
    environment:
      PORT: 3000
      # NOTE: POSTGRES_USER is defaulted to the image's name
      # POSTGRES_USER: pg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_NAMESPACE: "myblog_app"

    volumes:
      - .:/usr/src/app

    networks:
      - data

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432/tcp
    environment:
      # NOTE: This user declaration didn't work for some reason
      # POSTGRES_USER: pg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
      PGDATA: /var/lib/postgresql/data

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
      - postgres_configs:/etc/postgresql

    networks:
      - data

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379/tcp

    volumes:
      # - redis_data:/var/lib/redis
      - redis_data:/data

    networks:
      - data



volumes:
  postgres_data:
    driver: local
  postgres_logs:
    driver: local
  postgres_configs:
    driver: local

  redis_data:
    driver: local

networks:
  data:
