default: &default
  adapter:    postgresql
  database:   <%= ENV.fetch("POSTGRES_DB") %>
  host:       <%= ENV.fetch("POSTGRES_HOST") %>
  username:   <%= ENV.fetch("POSTGRES_USER") %>
  password:   <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool:       <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout:    5000

development:
  <<: *default
  # database: db/development.sqlite3
  database: <%= ENV.fetch("POSTGRES_DB") %>

test:
  <<: *default
  # database: db/test.sqlite3
  database: <%= ENV.fetch("POSTGRES_DB") %>

production:
  <<: *default
  # database: db/production.sqlite3
  database: <%= ENV.fetch("POSTGRES_DB") %>
